#############################################################################
##
##  b0_cocycle.g  --  Bogomolov multiplier B0(G) via the ORIGINAL definition,
##                    on an independent code path (no HAP).
##
##  B0(G) := Intersection over bicyclic A <= G of
##             Ker( res : H^2(G,Q/Z) -> H^2(A,Q/Z) ).
##
##  Two independent tools are provided.
##
##  (1) B0ViaSchurCover(G)
##      Dual computation M(G)/M0(G).  Uses the GAP core library and the
##      package "polycyclic" (Eick-Nickel-Horn), NOT HAP:
##        PcSchurCover(G) builds a finite Schur cover pi : S -> G as a pc group
##        from the Schur extension F/[R,F] (polycyclic: IsomorphismPcpGroup,
##        SchurExtensionEpimorphism, TorsionSubgroup, IsomorphismPcGroup), by
##        factoring out a free complement L of the torsion subgroup T of
##        R/[R,F]:  S := (F/[R,F]) / L,  M := T L / L  ~= T ~= M(G).
##        (GAP core's EpimorphismSchurCover returns an fp group whose subgroup
##         arithmetic is too slow for |M(G)| >= 2^6; it is kept as an optional
##         second route, see PcSchurCover's argument "core".)
##      Mathematics (see README.md, and SPEC_ja.md sections 2-3 for the proofs):
##        Let pi : S -> G be a Schur cover, M = Ker(pi) <= Z(S) meet [S,S].
##        The transgression delta_G : H_2(G,Z) -> M is an isomorphism, and for
##        A = <a,b> bicyclic with lifts a~, b~ in S one has
##           delta_G( Im( H_2(A,Z) -> H_2(G,Z) ) ) = < [a~,b~] >.
##        Hence  M0(G) ~= K := < [x,y] : x,y in S, [x,y] in M >  and
##               B0(G) ~= Hom( M/K , Q/Z ) ~= M/K  (finite abelian).
##      Trust boundary of (1): correctness of EpimorphismSchurCover (GAP core);
##      the code asserts at run time that M is central and M <= [S,S] and
##      that |M| = |H_2(G,Z)| given by AbelianInvariantsMultiplier (GAP core).
##
##  (2) B0Certificate(G)  /  VerifyB0Certificate(cert)
##      Cocycle-level certificate faithful to the original definition:
##        cert.mult : multiplication table of G  (n x n, entries in 1..n)
##        cert.e    : modulus
##        cert.c    : normalised 2-cocycle table G x G -> Z/e  (entries 0..e-1)
##      The verifier uses ONLY the tables (no pc presentation, no library
##      group).  It checks
##        (0) mult is a group table (associativity, identity, inverses);
##        (i) cocycle identity  c(g,h)+c(gh,k) = c(g,hk)+c(h,k)  mod e;
##        (ii) [c] != 0 in H^2(G,Q/Z): c/e is not a Q/Z-coboundary.  Two
##             equivalent tests are run:
##             (ii-a) linear algebra: no F : G -> Z/E with dF = (E/e)*c mod E,
##                    E := e * exp(G)   (Lemma 2.2 of the spec);
##             (ii-b) group theory: in the table group E_c = G x_c Z/e the
##                    central subgroup Z/e meets the derived subgroup
##                    non-trivially (Lemma 2.4 of the spec).
##        (iii) for every commuting pair (a,b):  c(a,b) = c(b,a) mod e
##              (Lemma 2.3: this is exactly "res_A [c] = 0 in H^2(A,Q/Z)"
##               for A = <a,b>).
##      The producer B0Certificate uses (1) to build c, but the VERIFIER never
##      touches the Schur cover.
##
##  Library functions relied on (GAP core + polycyclic; none from HAP):
##    polycyclic: IsomorphismPcpGroup, SchurExtensionEpimorphism,
##                TorsionSubgroup, Pcp/RelativeOrdersOfPcp, IsomorphismPcGroup
##    core: Kernel, PreImagesRepresentative, Comm, Centralizer,
##          ConjugacyClasses, Subgroup, NaturalHomomorphismByNormalSubgroup,
##          AbelianInvariants, AbelianInvariantsMultiplier (sanity check only),
##          IndependentGeneratorsOfAbelianGroup, IndependentGeneratorExponents,
##          Elements, SmithNormalFormIntegerMatTransforms, Exponent,
##          IdGroup (labels only), EpimorphismSchurCover (optional route only).
##
#############################################################################

#############################################################################
##  (1)  B0 via Schur cover
#############################################################################

##  Returns rec( inv := AbelianInvariants(M/K), M := M, K := K, pi := pi,
##               allpairs := <bool> )
##  If allpairs = true, K is generated by [a~,b~] over ALL commuting pairs
##  (a,b) in G x G (|G|^2 commutators).  If false, a runs over conjugacy class
##  representatives and b over a generating set of C_G(a); this suffices
##  because [a~, b1~ b2~] = [a~,b2~] [a~,b1~]^(b2~) = [a~,b1~][a~,b2~] (M central)
##  and [a~^g, b~^g] = [a~,b~]^g = [a~,b~].
LoadPackage("polycyclic", false);
B0_CHECK_AIM := "small";   # true / false / "small" (= only for |G| <= 2000)

##  PcSchurCover(G[, "core"]) : epimorphism pi : S -> G from a Schur cover S
##  given as a pc group (default route: polycyclic Schur extension; with the
##  optional string "core" the GAP-core EpimorphismSchurCover is returned
##  unchanged -- an fp group, slow for large M(G)).
PcSchurCover := function(arg)
  local G, isoP, Gp, ep, Ext, N, T, nat, Q, pcpQ, L, natL, S, isoS, Spc, imgs, pi;
  G := arg[1];
  if Length(arg) > 1 and arg[2] = "core" then return EpimorphismSchurCover(G); fi;
  isoP := IsomorphismPcpGroup(G);  Gp := Image(isoP);
  ep   := SchurExtensionEpimorphism(Gp);      # F/[R,F] -> F/R = Gp
  Ext  := Source(ep);  N := Kernel(ep);       # N = R/[R,F], central, f.g. abelian
  T    := TorsionSubgroup(N);                  # T = (R meet [F,F])/[R,F] ~= M(G)
  nat  := NaturalHomomorphismByNormalSubgroup(N, T);
  Q    := Image(nat);  pcpQ := Pcp(Q);
  if not ForAll(RelativeOrdersOfPcp(pcpQ), x -> x = 0) then
    Error("N/T is not presented as a free abelian group");
  fi;
  # free complement L of T in N (preimages of a Z-basis of N/T)
  L := Subgroup(N, List(GeneratorsOfPcp(pcpQ), q -> PreImagesRepresentative(nat, q)));
  if Size(Intersection(T, L)) <> 1 then Error("L meets T"); fi;
  natL := NaturalHomomorphismByNormalSubgroup(Ext, L);
  S    := Image(natL);                          # finite: |S| = |G| |M(G)|
  isoS := IsomorphismPcGroup(S);  Spc := Image(isoS);
  imgs := List(GeneratorsOfGroup(Spc), x ->
            PreImagesRepresentative(isoP,
              Image(ep, PreImagesRepresentative(natL, PreImagesRepresentative(isoS, x)))));
  pi := GroupHomomorphismByImagesNC(Spc, G, GeneratorsOfGroup(Spc), imgs);
  if Size(Spc) <> Size(G) * Size(T) then Error("|S| <> |G| |M(G)|"); fi;
  return pi;
end;

B0ViaSchurCoverData := function(G, allpairs)
  local pi, S, M, gens, ccl, a, b, at, bt, C, K, Q, els, i, j, invM;
  pi := PcSchurCover(G);
  S  := Source(pi);
  M  := Kernel(pi);
  # run-time sanity of the trust point "pi is a Schur cover":
  if not IsCentral(S, M) then Error("Schur cover kernel not central"); fi;
  if not IsSubgroup(DerivedSubgroup(S), M) then Error("Schur cover kernel not in [S,S]"); fi;
  # Independent check of |M| against GAP core's AbelianInvariantsMultiplier
  # (fp-group based; fast for |G| <= 2000, but it takes ~15 s per group and
  # can hit the coset-enumeration limit for |G| = 5^5).  Controlled by the
  # global B0_CHECK_AIM (default: only for |G| <= 2000).
  if B0_CHECK_AIM = true or (B0_CHECK_AIM = "small" and Size(G) <= 2000) then
    invM := AbelianInvariantsMultiplier(G);
    if Product(invM) <> Size(M) then Error("|Ker pi| <> |M(G)|"); fi;
  else
    invM := AbelianInvariants(M);   # from the polycyclic Schur extension only
  fi;
  if IsAbelian(G) then
    # every pair commutes, so K = <all commutators of S> = [S,S] >= M, B0 = 0
    return rec( inv := [], M := M, K := M, pi := pi, allpairs := allpairs, invM := invM );
  fi;
  gens := [];
  if allpairs then
    els := Elements(G);
    for i in [1..Length(els)] do
      at := PreImagesRepresentative(pi, els[i]);
      for j in [i+1..Length(els)] do
        if els[i]*els[j] = els[j]*els[i] then
          bt := PreImagesRepresentative(pi, els[j]);
          Add(gens, Comm(at, bt));
        fi;
      od;
    od;
  else
    ccl := List(ConjugacyClasses(G), Representative);
    for a in ccl do
      if IsOne(a) then continue; fi;
      at := PreImagesRepresentative(pi, a);
      C  := Centralizer(G, a);
      for b in GeneratorsOfGroup(C) do
        bt := PreImagesRepresentative(pi, b);
        Add(gens, Comm(at, bt));
      od;
    od;
  fi;
  # membership in M = Ker(pi) is tested through pi (cheap; avoids coset
  # enumeration in the fp cover):
  if not ForAll(gens, x -> IsOne(Image(pi, x))) then Error("commutator of commuting lifts not in M"); fi;
  K := Subgroup(M, gens);
  Q := M / K;
  return rec( inv := AbelianInvariants(Q), M := M, K := K, pi := pi,
              allpairs := allpairs, invM := invM );
end;

##  Abelian invariants of B0(G) (same format as HAP's BogomolovMultiplier).
B0ViaSchurCover := function(G)
  return B0ViaSchurCoverData(G, false).inv;
end;

#############################################################################
##  (2)  Certificate producer
#############################################################################

##  Multiplication table of G on the list els (els[1] must be the identity).
MultTableOf := function(els)
  local n, pos, i, j, T;
  n := Length(els);
  pos := function(x) return Position(els, x); end;
  T := List([1..n], i -> List([1..n], j -> pos(els[i]*els[j])));
  return T;
end;

##  Produce a certificate for "B0(G) <> 0".  Returns fail if B0(G) = 0.
##  The cocycle is  c(g,h) = chi( s(g) s(h) s(gh)^-1 )  where s is a section
##  of the Schur cover and chi : M -> M/K -> Z/e is the projection onto the
##  first cyclic factor of M/K (e = its order).
B0Certificate := function(G)
  local D, pi, S, M, K, nat, Q, indep, e, z, chi, els, n, sec, c, i, j, gh, T,
        idG;
  D := B0ViaSchurCoverData(G, false);
  if D.inv = [] then return fail; fi;
  pi := D.pi; S := Source(pi); M := D.M; K := D.K;
  nat := NaturalHomomorphismByNormalSubgroup(M, K);
  Q := Range(nat);
  indep := IndependentGeneratorsOfAbelianGroup(Q);
  z := indep[1];  e := Order(z);
  # chi : Q -> Z/e, projection onto <z> along the other independent generators
  chi := function(m)
    local q, exps;
    q := Image(nat, m);
    exps := IndependentGeneratorExponents(Q, q);
    return exps[1] mod e;
  end;
  els := ShallowCopy(Elements(G));
  # put identity first
  i := Position(els, One(G));
  if i <> 1 then els := Concatenation([els[i]], els{Difference([1..Length(els)],[i])}); fi;
  n := Length(els);
  sec := List(els, g -> PreImagesRepresentative(pi, g));
  sec[1] := One(S);                      # normalised section
  T := MultTableOf(els);
  c := List([1..n], i -> List([1..n], j -> 0));
  for i in [1..n] do
    for j in [1..n] do
      gh := T[i][j];
      c[i][j] := chi( sec[i]*sec[j]*sec[gh]^-1 );
    od;
  od;
  if Size(G) <= 2000 then idG := IdGroup(G); else idG := fail; fi;
  return rec( id := idG, n := n, mult := T, e := e, c := c,
              B0inv := D.inv, Minv := D.invM, exp := Exponent(G) );
end;

#############################################################################
##  (2)  Certificate verifier  -- uses only cert.mult, cert.e, cert.c
#############################################################################

##  Solve  F(g)+F(h)-F(gh) = rhs(g,h)  (mod E)  for F : {1..n} -> Z/E over the
##  listed pairs; returns true iff solvable.  Uses Smith normal form over Z.
##  Unknowns: F_1..F_n plus one slack integer per equation (for the modulus).
SolvableModE := function(n, pairs, rhs, E)
  local eq, A, snf, m, k, i, d, y, bvec, P, di;
  # A x = b (mod E) with A an m x n integer matrix.  With P A Q = D (Smith
  # normal form, P,Q unimodular) this is D y = P b (mod E), y = Q^-1 x, so it is
  # solvable iff for every row i:  gcd(d_i, E) divides (P b)_i   (d_i := 0 for
  # rows beyond the rank, i.e. (P b)_i = 0 mod E).
  m := Length(pairs);
  A := List([1..m], i -> ListWithIdenticalEntries(n, 0));
  bvec := [];
  for k in [1..m] do
    eq := pairs[k];
    A[k][eq[1]] := A[k][eq[1]] + 1;
    A[k][eq[2]] := A[k][eq[2]] + 1;
    A[k][eq[3]] := A[k][eq[3]] - 1;
    Add(bvec, rhs[k]);
  od;
  snf := SmithNormalFormIntegerMatTransforms(A);
  d := snf.normal; P := snf.rowtrans;
  y := P * bvec;
  for i in [1..m] do
    if i <= n then di := d[i][i]; else di := 0; fi;
    if y[i] mod Gcd(di, E) <> 0 then return false; fi;
  od;
  return true;
end;

##  Verify a certificate.  Returns a record with fields
##    group_table, cocycle, nontrivial_linalg, nontrivial_group, bicyclic_symmetric,
##    ok  (the conjunction), and timings.
##  Options: full := true forces the full |G|^2-equation system in (ii-a)
##  (default: generator-reduced system, Lemma 2.2(b) of the spec).
VerifyB0Certificate := function(arg)
  local cert, opts, T, n, e, c, i, j, k, ok, res, t0, inv, ident, gens, closure,
        new, x, s, pairs, rhs, E, expG, ord, m, g, p, sizeE, elsE, mulE, invE,
        comm, D, Dset, frontier, y, z, w, u, h, cnt, full, ce, ne, idxE, q, r,
        ordOf, commuting, sym, gh, kk, hk;
  cert := arg[1];
  full := Length(arg) > 1 and arg[2] = true;
  T := cert.mult; n := cert.n; e := cert.e; c := cert.c;
  res := rec();
  # ---- (0) group table --------------------------------------------------
  t0 := Runtime();
  ok := ForAll([1..n], i -> T[1][i] = i and T[i][1] = i);            # identity = 1
  ok := ok and ForAll([1..n], i -> Set(T[i]) = [1..n]);              # latin rows
  ok := ok and ForAll([1..n], i -> Set(List([1..n], j -> T[j][i])) = [1..n]);
  if ok then
    for i in [1..n] do for j in [1..n] do
      gh := T[i][j];
      for k in [1..n] do
        if T[gh][k] <> T[i][T[j][k]] then ok := false; fi;
      od;
    od; od;
  fi;
  res.group_table := ok;
  inv := List([1..n], i -> First([1..n], j -> T[i][j] = 1));        # inverses
  res.t_group := Runtime() - t0;
  # exponent of G from the table
  ordOf := function(i)
    local o, x; o := 1; x := i;
    while x <> 1 do x := T[x][i]; o := o + 1; od; return o;
  end;
  expG := Lcm(List([1..n], ordOf));
  res.expG := expG;
  # ---- (i) cocycle identity ---------------------------------------------
  t0 := Runtime();
  ok := ForAll([1..n], i -> c[1][i] mod e = 0 and c[i][1] mod e = 0);   # normalised
  if ok then
    for i in [1..n] do for j in [1..n] do
      gh := T[i][j];
      for k in [1..n] do
        hk := T[j][k];
        if (c[i][j] + c[gh][k] - c[i][hk] - c[j][k]) mod e <> 0 then ok := false; fi;
      od;
    od; od;
  fi;
  res.cocycle := ok;
  res.t_cocycle := Runtime() - t0;
  # ---- (iii) bicyclic restrictions vanish --------------------------------
  t0 := Runtime();
  sym := true; cnt := 0;
  for i in [1..n] do for j in [i+1..n] do
    if T[i][j] = T[j][i] then
      cnt := cnt + 1;
      if (c[i][j] - c[j][i]) mod e <> 0 then sym := false; fi;
    fi;
  od; od;
  res.bicyclic_symmetric := sym;
  res.n_commuting_pairs := cnt;
  res.t_bicyclic := Runtime() - t0;
  # ---- (ii-a) non-triviality by linear algebra over Z/E ------------------
  t0 := Runtime();
  E := e * expG;  m := E / e;
  # generating set of G from the table (greedy)
  gens := []; closure := [1];
  for x in [2..n] do
    if not x in closure then
      Add(gens, x);
      # close
      new := true;
      closure := Set(closure);
      frontier := ShallowCopy(closure);
      while new do
        new := false;
        for y in ShallowCopy(closure) do for s in gens do
          z := T[y][s];
          if not z in closure then AddSet(closure, z); new := true; fi;
        od; od;
      od;
    fi;
  od;
  res.generators := gens;
  pairs := []; rhs := [];
  if full then
    for i in [1..n] do for j in [1..n] do
      Add(pairs, [i, j, T[i][j]]); Add(rhs, (m * c[i][j]) mod E);
    od; od;
  else
    for s in gens do for j in [1..n] do
      Add(pairs, [s, j, T[s][j]]); Add(rhs, (m * c[s][j]) mod E);
    od; od;
  fi;
  res.nontrivial_linalg := not SolvableModE(n, pairs, rhs, E);
  res.E := E; res.linalg_full := full; res.n_equations := Length(pairs);
  res.t_linalg := Runtime() - t0;
  # ---- (ii-b) non-triviality by the extension group E_c ------------------
  # elements of E_c: (g,z) encoded as (g-1)*e + z + 1 ; product
  # (g,z)(h,w) = (gh, z+w+c(g,h)).
  t0 := Runtime();
  sizeE := n * e;
  idxE := function(g, z) return (g-1)*e + (z mod e) + 1; end;
  mulE := function(u, v)
    local g, z, h, w;
    g := QuoInt(u-1, e) + 1; z := (u-1) mod e;
    h := QuoInt(v-1, e) + 1; w := (v-1) mod e;
    return idxE(T[g][h], z + w + c[g][h]);
  end;
  invE := function(u)
    local g, z, gi;
    g := QuoInt(u-1, e) + 1; z := (u-1) mod e; gi := inv[g];
    # (g,z)(gi,w) = (1, z+w+c(g,gi)) = identity  =>  w = -z - c(g,gi)
    return idxE(gi, -z - c[g][gi]);
  end;
  # all commutators [x~,y~] with x~=(x,0), y~=(y,0); note [(x,z),(y,w)] is the same
  Dset := Set([]);
  for i in [1..n] do for j in [1..n] do
    u := idxE(i,0); w := idxE(j,0);
    comm := mulE(mulE(invE(u), invE(w)), mulE(u, w));
    AddSet(Dset, comm);
  od; od;
  # subgroup generated by Dset (closure under multiplication; finite group)
  D := ShallowCopy(Dset); frontier := ShallowCopy(Dset);
  while Length(frontier) > 0 do
    new := [];
    for x in frontier do for y in Dset do
      z := mulE(x, y);
      if not z in D then AddSet(D, z); Add(new, z); fi;
    od; od;
    frontier := new;
  od;
  # D meets the central Z/e = {(1,z)} non-trivially?
  res.nontrivial_group := ForAny([1..e-1], z -> idxE(1, z) in D);
  res.derived_size := Length(D);
  res.t_group_ext := Runtime() - t0;
  res.ok := res.group_table and res.cocycle and res.bicyclic_symmetric
            and res.nontrivial_linalg and res.nontrivial_group;
  return res;
end;

#############################################################################
##  Cross-check driver
#############################################################################

##  Read the HAP result file b0_order_<n>.txt (list of [id, invariants]).
ReadHAPResults := function(n)
  local str, f;
  f := Concatenation("b0_order_", String(n), ".txt");
  str := StringFile(f);
  if str = fail then
    # also look in results/, where this repository keeps the recorded runs
    str := StringFile(Concatenation("results/", f));
  fi;
  if str = fail then return fail; fi;
  return EvalString(str);
end;

##  Compare B0ViaSchurCover with HAP file on the given list of ids.
##  Returns rec(agree, disagree := list of [id, ours, hap], time).
B0CrossCheck := function(n, ids)
  local hap, haprec, id, ours, h, agree, dis, t0, nontriv;
  hap := ReadHAPResults(n);
  haprec := rec();
  for h in hap do haprec.(String(h[1])) := h[2]; od;
  agree := 0; dis := []; nontriv := [];
  t0 := Runtime();
  for id in ids do
    ours := B0ViaSchurCover(SmallGroup(n, id));
    if IsBound(haprec.(String(id))) then h := haprec.(String(id)); else h := []; fi;
    if ours = h then agree := agree + 1; else Add(dis, [id, ours, h]); fi;
    if ours <> [] then Add(nontriv, [id, ours]); fi;
  od;
  return rec( order := n, checked := Length(ids), agree := agree, disagree := dis,
              nontrivial := nontriv, time_s := (Runtime()-t0)/1000.0 );
end;

#############################################################################
##  Negative control: a certificate-shaped object for a class of H^2(G,Q/Z)
##  that is non-zero but NOT in B0(G) (exists iff M0(G) <> 0, i.e. K <> 1).
##  The verifier must accept (i),(ii) and reject (iii).
#############################################################################
NonB0ControlCertificate := function(G)
  local D, pi, S, M, K, indep, z, e, chi, els, n, sec, c, i, j, gh, T, gensK, idx;
  D := B0ViaSchurCoverData(G, false);
  pi := D.pi; S := Source(pi); M := D.M; K := D.K;
  if Size(K) = 1 then return fail; fi;
  # chi : M -> Z/e, projection onto one independent generator of M (index
  # idx), chosen so that chi does not kill K (try each generator).
  indep := IndependentGeneratorsOfAbelianGroup(M);
  chi := fail;
  for idx in [1..Length(indep)] do
    e := Order(indep[idx]);
    if ForAny(GeneratorsOfGroup(K), k -> IndependentGeneratorExponents(M, k)[idx] mod e <> 0) then
      break;
    fi;
    idx := fail;
  od;
  if idx = fail then return fail; fi;
  e := Order(indep[idx]);
  chi := function(m) return IndependentGeneratorExponents(M, m)[idx] mod e; end;
  els := ShallowCopy(Elements(G));
  i := Position(els, One(G));
  if i <> 1 then els := Concatenation([els[i]], els{Difference([1..Length(els)],[i])}); fi;
  n := Length(els);
  sec := List(els, g -> PreImagesRepresentative(pi, g)); sec[1] := One(S);
  T := MultTableOf(els);
  c := List([1..n], i -> List([1..n], j -> 0));
  for i in [1..n] do for j in [1..n] do
    gh := T[i][j]; c[i][j] := chi( sec[i]*sec[j]*sec[gh]^-1 );
  od; od;
  return rec( id := IdGroup(G), n := n, mult := T, e := e, c := c, control := "non-B0 class" );
end;

#############################################################################
##  Batch drivers (write results to files)
#############################################################################

##  Cross-check all groups of order n (or the ids given) against the HAP file
##  and append a summary to b0_cocycle_crosscheck.log.
B0CrossCheckOrder := function(n, ids, tag)
  local r, f, s;
  r := B0CrossCheck(n, ids);
  s := Concatenation("order ", String(n), " [", tag, "]: checked ", String(r.checked),
        " agree ", String(r.agree), " disagree ", String(Length(r.disagree)),
        " nontrivial(ours) ", String(Length(r.nontrivial)), " time ", String(r.time_s), " s\n");
  Print(s);
  AppendTo("b0_cocycle_crosscheck.log", s);
  if r.disagree <> [] then AppendTo("b0_cocycle_crosscheck.log", "  DISAGREE: ", r.disagree, "\n"); fi;
  PrintTo(Concatenation("b0_cocycle_order_", String(n), "_", tag, ".txt"), r.nontrivial, "\n");
  return r;
end;

##  Produce + verify certificates for the given ids of order n; log results.
B0CertifyOrder := function(n, ids, full)
  local id, cert, v, s, t0, G;
  for id in ids do
    G := SmallGroup(n, id);
    t0 := Runtime();
    cert := B0Certificate(G);
    if cert = fail then
      s := Concatenation("cert ", String(n), "#", String(id), ": B0=0 (no certificate)\n");
    else
      v := VerifyB0Certificate(cert, full);
      s := Concatenation("cert ", String(n), "#", String(id), ": e=", String(cert.e),
            " B0=", String(cert.B0inv), " M=", String(cert.Minv),
            " table=", String(v.group_table), " cocycle=", String(v.cocycle),
            " nontriv_linalg=", String(v.nontrivial_linalg), "(", String(v.n_equations), " eqs, E=", String(v.E), ")",
            " nontriv_group=", String(v.nontrivial_group),
            " bicyclic_sym=", String(v.bicyclic_symmetric), "(", String(v.n_commuting_pairs), " pairs)",
            " OK=", String(v.ok), " time=", String((Runtime()-t0)/1000.0), " s\n");
    fi;
    Print(s); AppendTo("b0_cocycle_certs.log", s);
  od;
end;
